// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCc4q10USnuPaR_6w0BBweegUDMzvtr2I',
    appId: '1:525412561327:web:e1ab1b5e6203fa12797f5a',
    messagingSenderId: '525412561327',
    projectId: 'noble-bank-64cd0',
    authDomain: 'noble-bank-64cd0.firebaseapp.com',
    storageBucket: 'noble-bank-64cd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjpKlx5L2HwV0I5Z28G5cLjagFZWEtaJ4',
    appId: '1:525412561327:android:790ac97c921e2469797f5a',
    messagingSenderId: '525412561327',
    projectId: 'noble-bank-64cd0',
    storageBucket: 'noble-bank-64cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYK3l00OnRegkBVBMJLwh-drYKZqyjkOk',
    appId: '1:525412561327:ios:808a63ab489c00f2797f5a',
    messagingSenderId: '525412561327',
    projectId: 'noble-bank-64cd0',
    storageBucket: 'noble-bank-64cd0.appspot.com',
    iosClientId: '525412561327-qts86tu3c6h4de4qkovb5hh6iurc5p6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybankapp',
  );
}
